package employee;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.*;

@DynamoDBTable(tableName=Config.DYNAMODB_TABLE_NAME)
public class Employee {
	private UUID id;
	private String forename;
	private String surname;
	private String dateOfBirth;
	private String jobTitle;

	public Employee() {	}
	
	public Employee(String forename, String surname, String dateOfBirth, String jobTitle) {
		this.setId(UUID.randomUUID());
		this.setForename(forename);
		this.setSurname(surname);
		this.setDateOfBirth(dateOfBirth);
		this.setJobTitle(jobTitle);
	}
	
	public Employee(UUID id, String forename, String surname, String dateOfBirth, String jobTitle) { 
		this.setId(id);
		this.setForename(forename);
		this.setSurname(surname);
		this.setDateOfBirth(dateOfBirth);
		this.setJobTitle(jobTitle);
	}
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public UUID getId() {
		return this.id;
	} 
	
	@DynamoDBAttribute(attributeName="forename")
	public String getForename() {
		return this.forename;
	} 
	
	@DynamoDBAttribute(attributeName="surname")
	public String getSurname() {
		return this.surname;
	} 
	
	@DynamoDBAttribute(attributeName="dateOfBirth")
	public String getDateOfBirth() {
		return this.dateOfBirth;
	} 
	
	@DynamoDBAttribute(attributeName="jobTitle")
	public String getJobTitle() {
		return this.jobTitle;
	} 

	public void setId(UUID newId) {
		this.id = newId; 
	}
	
	public void setForename(String forename) {
		this.forename = forename;
	}
	
	public void setSurname(String surname) {
		this.surname = surname;
	}
	
	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}
	
}
